import os

CRM_TYPE = os.getenv('CRM_TYPE', 'salesforce')
SALESFORCE_CLIENT_ID = os.getenv('SALESFORCE_CLIENT_ID')
SALESFORCE_CLIENT_SECRET = os.getenv('SALESFORCE_CLIENT_SECRET')
HUBSPOT_API_KEY = os.getenv('HUBSPOT_API_KEY')
PIPEDRIVE_API_KEY = os.getenv('PIPEDRIVE_API_KEY')
MODEL_PATH = 'models/lead_scoring_model.pkl'
HOT_LEAD_THRESHOLD = 70
WARM_LEAD_THRESHOLD = 40
API_HOST = '0.0.0.0'
API_PORT = 8000